### PR TITLE
Bump Drupal 8.6 to 8.7 

### PR DESCRIPTION
**Pull request by martinfrances107**
Updated composer.json

### CODE REVIEW

**Comment by dawehner** [comment]
I asked in slack for an opinion. For me at least this makes totally sense. When we go with 8.7 I'm wondering whether it makes sense to pin down the version

**Comment by lauriii** [comment]
Why would we pin down a specific version?

**Comment by dawehner** [comment]
> Why would we pin down a specific version?

My idea was: A random Drupal core commit could break the demo

**Comment by dawehner** [comment]
Oh yeah you are absolute right!

**Comment by lauriii** [comment]
Should we update the composer.lock as well?

**Comment by dawehner** [comment]
Yeah I guess so, should we revert?

**Comment by lauriii** [comment]
I'm fine with a follow-up PR

**Pull request merged**
